DROP TABLE MEMBER;

CREATE TABLE MEMBER
(
ID      VARCHAR2(50),
PWD     NVARCHAR2(50),
NAME    NVARCHAR2(50),
GENDER  NCHAR(2),
AGE     NUMBER,
BIRTHDAY CHAR(10 BYTE),
PHONE   CHAR(13 BYTE),
REGDATE DATE
);

ALTER TABLE MEMBER MODIFY ID NVARCHAR2(50);
ALTER TABLE MEMBER DROP COLUMN AGE;
ALTER TABLE MEMBER ADD EMAIL VARCHAR2(200);

CREATE TABLE NOTICE
(
    ID      NUMBER,
    TITLE       NVARCHAR2(100),
    WRITER_ID   NVARCHAR2(50),
    CONTENT     CLOB,
    REGDATE     TIMESTAMP,
    HIT         NUMBER,
    FILES       NVARCHAR2(100)
);

CREATE TABLE "COMMENT"
(
    ID          NUMBER,
    CONTENT     NVARCHAR2(2000),
    REGDAE      TIMESTAMP,
    WRITER_ID   NVARCHAR2(50),
    NOTICE_ID   NUMBER
    );
    
CREATE TABLE ROLE
(
    ID      VARCHAR2(50),
    DISCRIPTION NVARCHAR2(500)
    );
    
CREATE TABLE MEMBER_ROLE
(
    MEMBER_ID NVARCHAR2(50),
    ROLE_ID     VARCHAR2(50)
    );

INSERT INTO MEMBER(ID, PWD) VALUES('newlec', '111');
INSERT INTO MEMBER(ID, PWD) VALUES('dragon', '111');
SELECT * FROM MEMBER;

SELECT * FROM NOTICE;

INSERT INTO NOTICE VALUES(1, 'JDB란 무엇인가?', 'newlec', aaa, DATE, 1);