DROP TABLE MEMBER;

CREATE TABLE MEMBER
(
ID      VARCHAR2(50),
PWD     NVARCHAR2(50),
NAME    NVARCHAR2(50),
GENDER  NCHAR(2),
AGE     NUMBER,
BIRTHDAY CHAR(10 BYTE),
PHONE   CHAR(13 BYTE),
REGDATE DATE
);

ALTER TABLE MEMBER MODIFY ID NVARCHAR2(50);
ALTER TABLE MEMBER DROP COLUMN AGE;
ALTER TABLE MEMBER ADD EMAIL VARCHAR2(200);

CREATE TABLE NOTICE
(
    ID      NUMBER,
    TITLE       NVARCHAR2(100),
    WRITER_ID   NVARCHAR2(50),
    CONTENT     CLOB,
    REGDATE     TIMESTAMP,
    HIT         NUMBER,
    FILES       NVARCHAR2(100)
);

CREATE TABLE "COMMENT"
(
    ID          NUMBER,
    CONTENT     NVARCHAR2(2000),
    REGDAE      TIMESTAMP,
    WRITER_ID   NVARCHAR2(50),
    NOTICE_ID   NUMBER
    );
    
CREATE TABLE ROLE
(
    ID      VARCHAR2(50),
    DISCRIPTION NVARCHAR2(500)
    );
    
CREATE TABLE MEMBER_ROLE
(
    MEMBER_ID NVARCHAR2(50),
    ROLE_ID     VARCHAR2(50)
    );

INSERT INTO MEMBER(ID, PWD) VALUES('newlec', '111');
INSERT INTO MEMBER(ID, PWD) VALUES('dragon', '111');
SELECT * FROM MEMBER;

SELECT * FROM NOTICE;

SELECT * FROM MEMBER;

INSERT INTO MEMBER(ID, PWD)
VALUES('newlec', '111');

INSERT 
INTO NOTICE(ID, TITLE, WRITER_ID, CONTENT, REGDATE, HIT)
VALUES(1, 'JDB란 무엇인가?', 'LHS', 'HELELO', SYSDATE, 1);

INSERT 
INTO NOTICE(ID, TITLE, WRITER_ID, CONTENT, REGDATE, HIT)
VALUES(2, 'JDB드라이버 다운로드 방법?', 'dragon', 'bbb', SYSDATE, 10);

INSERT 
INTO NOTICE(ID, TITLE, WRITER_ID, CONTENT, REGDATE, HIT)
VALUES(3, '파라미터를 가지는 문장 실행하기?', 'okay', 'ccca', SYSDATE, 15);

INSERT 
INTO NOTICE(ID, TITLE, WRITER_ID, CONTENT, REGDATE, HIT)
VALUES(4, 'JSP에서 JDBD사용하기', 'quest', 'ddddd', SYSDATE, 23);

INSERT 
INTO NOTICE(ID, TITLE, WRITER_ID, CONTENT, REGDATE, HIT)
VALUES(5, 'Service 계층 사용하기', 'hi', 'eeee', SYSDATE, 5);

INSERT 
INTO NOTICE(ID, TITLE, WRITER_ID, CONTENT, REGDATE, HIT)
VALUES(6, '전화번호로 연락주시기 바랍니다. 010-1234-5678', 'hello h', 'fff', SYSDATE, 3);

INSERT 
INTO NOTICE(ID, TITLE, WRITER_ID, CONTENT, REGDATE, HIT)
VALUES(7, '선반-접시-그릇 이 세가지요~~', 'michel j', '연착처를 남깁니다.', SYSDATE, 50);

INSERT 
INTO NOTICE(ID, WRITER_ID, REGDATE, HIT)
VALUES(8,  'newlec', SYSDATE, 10);

SELECT * FROM NOTICE;
COMMIT;